### ISSUE TITLE
How would I use this? What is it good for? Is there an explanation of what it does someplace?

### ISSUE THREAD

**Issue by hoytstah** [DaniilSokolyuk/SimpleRpc#1]
Did you write a CodeProject article or something, so potential users of your library can acquire a clue about how to use it? If you think the readme is sufficient -- you're incredibly wrong or I'm dumb or both. ;)

Link to CodeProject (or similar) article please:

**Comment by DaniilSokolyuk** [comment]
Hello @hoytstah, thank you.
I have plans to make complete documentation on github pages
You can find sample project here https://github.com/DaniilSokolyuk/SimpleRpc/tree/master/sample,

**Comment by Seeker1437** [comment]
Can this be used for non asp applications?

**Comment by DaniilSokolyuk** [comment]
@Seeker1437, hello, server side part supports only asp net .core, client you can use for non asp application, you can build service provider and get required service or convert IServicwCollection to your IOC container for example https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/65352f4a5ad1b29386cfccb39944ce566e5a0e79/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L85,
ServiceColletion supports many containers https://github.com/aspnet/DependencyInjection
