### ISSUE TITLE
My improvements

### ISSUE THREAD

**Issue by BBGONE** [DaniilSokolyuk/SimpleRpc#4]
Hi, i took your project for playing with it -
and did some modifications - added HttpClientFactory (it is configured at the time of the service registration), and everywhere the IServiceProvider is used i added scopes - to control lifetimes of dependencies which could be injected (without it the ServiceProvider keeps references even to transient services until it is disposed - and on the server side it can lead to memory leak). And we can not use  transient services inside a singleton service, but can use singletons inside the transient ones. So it's better to use a transient service scope on the server side.

https://github.com/BBGONE/SimpleRpc-Fork

**Comment by DaniilSokolyuk** [comment]
Hi BBGONE
Thank you very much, this changes looks good to me!
You can create PR or i can make these changes myself in two weeks

**Comment by BBGONE** [comment]
I currently played with it. I think it can be useful in the future in my projects. You better do it yourself, because i have not much time at work. I think the HttpClientFactory is better, because it allows to create HttpClient for each request and not to keep a single instance, which in case of communication failure must be replaced with a new one. And there exist https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory which adds additional robustness to the HttpClient.

**Comment by DaniilSokolyuk** [comment]
In master now
I will release the nuget today
